### ISSUE TITLE
Support select0 and rank0 by default

### ISSUE THREAD

**Issue by IcaroG** [saskeli/bit_vector#1]
Hello! Would love to have support for both `select0` and `rank0` operations by default in the bitvector.

Thanks

**Comment by IcaroG** [comment]
Oh, I just noticed I was using the wrong lib and you already have these operations implemented! Sorry.;

**Comment by saskeli** [comment]
Haha. That's ok.

Note that `select0` is slow in comparison to all the other operations. If you need fast `select0`, it would need to be implemented properly.

**Comment by IcaroG** [comment]
Do you plan on improving the `select0` implementation soon?

**Comment by saskeli** [comment]
Depends on your definition of soon. I'm pretty swamped until mid May. And then I'll get back to this project. If a faster `select0` is a desirable feature and not too hard to implement, I could do it then.

The alternative is for you to do it yourself (and preferably make a pull request). It should work very similarly to `select1` but with `64 - popcount` for words.

**Comment by IcaroG** [comment]
I don't think I will have time to do it myself now because I have a deadline in April, and since it's already working for me (even if not 100% optimized),  I will prioritize finishing everything else first.

But I may come back after the deadline to implement this part.
